./hw4runscript SPEC bzip2 Hawkeye
./hw4runscript SPEC gcc Hawkeye
./hw4runscript SPEC hmmer Hawkeye
./hw4runscript SPEC sjeng Hawkeye
./hw4runscript SPEC xalan Hawkeye
./hw4runscript SPEC cactusADM Hawkeye
./hw4runscript SPEC namd Hawkeye
./hw4runscript SPEC calculix Hawkeye
./hw4runscript SPEC mcf Hawkeye
./hw4runscript SPEC libquantum Hawkeye
./hw4runscript SPEC milc Hawkeye
./hw4runscript SPEC leslie3d Hawkeye
./hw4runscript SPEC soplex Hawkeye
./hw4runscript SPEC lbm Hawkeye
